name: Test script
on: [push, pull_request]
jobs:
  Test-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff Lint
        uses: chartboost/ruff-action@v1
        with:
          args: '--select=ALL --ignore=E501,D100,INP001,PTH123,TRY003,E701,N999,ERA001,D,PT,FA,T'

      - name: Test
        run: |
          python -m unittest discover tests

      - name: Run
        run: |
          python main.py