name: Test script
on: [push, pull_request]
jobs:
  Test-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt ruff

      - name: Ruff Lint
        run: ruff check

      - name: Test
        run: |
          python -m unittest discover tests

      - name: Run
        run: |
          python main.py