name: Test script
on: [push, pull_request]
jobs:
  Test-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: '--target-version=py312 --select=ALL --ignore=T201,E501'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run
        run: |
          python main.py