name: Test script
on: [push, pull_request]
jobs:
  Test-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff Lint
        uses: chartboost/ruff-action@v1
        with:
          args: '--select=ALL --ignore=A001,ANN,D,E501,FIX00,INP001,PLR,S101,T201,TD00,ERA001,PTH123,FA102'

      - name: Test
        run: |
          python -m unittest discover tests

      - name: Run
        run: |
          python main.py